#ifndef NS_CORE_NET_IP6_H_
#define NS_CORE_NET_IP6_H_

enum {
    IP6_DEFAULT_HOP_LIMIT   = NS_CONFIG_IPV6_DEFAULT_HOP_LIMIT,
    IP6_MAX_DATAGRAM_LENGTH = NS_CONFIG_IPV6_DEFAULT_MAX_DATAGRAM,
};

#endif // NS_CORE_NET_IP6_H_
