#ifndef NS_CORE_DEFAULT_CONFIG_H_
#define NS_CORE_DEFAULT_CONFIG_H_

#ifndef NS_CONFIG_CLI_MAX_LINE_LEN
#define NS_CONFIG_CLI_MAX_LINE_LEN 128
#endif

#ifndef NS_CONFIG_CLI_RX_BUFFER_SIZE
#define NS_CONFIG_CLI_RX_BUFFER_SIZE 512
#endif

#ifndef NS_CONFIG_CLI_TX_BUFFER_SIZE
#define NS_CONFIG_CLI_TX_BUFFER_SIZE 1024
#endif

#ifndef NS_CONFIG_MESSAGE_NUM_BUFFERS
#define NS_CONFIG_MESSAGE_NUM_BUFFERS 44
#endif

#ifndef NS_CONFIG_MESSAGE_BUFFER_SIZE
#define NS_CONFIG_MESSAGE_BUFFER_SIZE 128
#endif

#ifndef NS_CONFIG_ENABLE_TIME_SYNC
#define NS_CONFIG_ENABLE_TIME_SYNC 0
#endif

#ifndef NS_CONFIG_HEADER_IE_SUPPORT
#if NS_CONFIG_ENABLE_TIME_SYNC
#define NS_CONFIG_HEADER_IE_SUPPORT 1
#else
#define NS_CONFIG_HEADER_IE_SUPPORT 0
#endif
#endif

#ifndef NS_CONFIG_JOIN_BEACON_VERSION
#define NS_CONFIG_JOIN_BEACON_VERSION MAC_BEACON_PAYLOAD_PROTOCOL_VERSION
#endif

#endif // NS_CORE_DEFAULT_CONFIG_H_
