#ifndef NS_ERROR_H_
#define NS_ERROR_H_

typedef enum _ns_error {
    NS_ERROR_NONE = 0,
    NS_ERROR_FAILED = 1,
    NS_ERROR_DROP = 2,
    NS_ERROR_NO_BUFS = 3,
    NS_ERROR_NO_ROUTE = 4,
    NS_ERROR_BUSY = 5,
    NS_ERROR_PARSE = 6,
    NS_ERROR_INVALID_ARGS = 7,
    NS_ERROR_SECURITY = 8,
    NS_ERROR_ADDRESS_QUERY = 9,
    NS_ERROR_NO_ADDRESS = 10,
    NS_ERROR_ABORT = 11,
    NS_ERROR_NOT_IMPLEMENTED = 12,
    NS_ERROR_INVALID_STATE = 13,
    NS_ERROR_NO_ACK = 14,
    NS_ERROR_CHANNEL_ACCESS_FAILURE = 15,
    NS_ERROR_DETACHED = 16,
    NS_ERROR_FCS = 17,
    NS_ERROR_NO_FRAME_RECEIVED = 18,
    NS_ERROR_UNKNOWN_NEIGHBOR = 19,
    NS_ERROR_INVALID_SOURCE_ADDRESS = 20,
    NS_ERROR_ADDRESS_FILTERED = 21,
    NS_ERROR_DESTINATION_ADDRESS_FILTERED = 22,
    NS_ERROR_NOT_FOUND = 23,
    NS_ERROR_ALREADY = 24,
    NS_ERROR_IP6_ADDRESS_CREATION_FAILURE = 26,
    NS_ERROR_NOT_CAPABLE = 27,
    NS_ERROR_RESPONSE_TIMEOUT = 28,
    NS_ERROR_DUPLICATED = 29,
    NS_ERROR_REASSEMBLY_TIMEOUT = 30,
    NS_ERROR_NOT_TMF = 31,
    NS_ERROR_NOT_LOWPAN_DATA_FRAME = 32,
    NS_ERROR_DISABLED_FEATURE = 33,
    NS_ERROR_LINK_MARGIN_LOW = 34,
    NS_ERROR_GENERIC = 255,
} ns_error_t;

const char *
ns_error_to_string(ns_error_t error);

#endif // NS_ERROR_H_
