#ifndef NS_CORE_UNIX_CONFIG_H_
#define NS_CORE_UNIX_CONFIG_H_

#define NS_CONFIG_PLATFORM_INFO "UNIX"

#ifndef NS_CONFIG_LOG_OUTPUT
#define NS_CONFIG_LOG_OUTPUT NS_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED
#endif

#if NS_RADIO
#ifndef NS_CONFIG_ENABLE_SOFTWARE_ACK_TIMEOUT
#define NS_CONFIG_ENABLE_SOFTWARE_ACK_TIMEOUT 1
#endif

#ifndef NS_CONFIG_ENABLE_SOFTWARE_ENERGY_SCAN
#define NS_CONFIG_ENABLE_SOFTWARE_ENERGY_SCAN 1
#endif

#ifndef NS_CONFIG_ENABLE_SOFTWARE_RETRANSMIT
#define NS_CONFIG_ENABLE_SOFTWARE_RETRANSMIT 1
#endif

#ifndef NS_CONFIG_ENABLE_SOFTWARE_CSMA_BACKOFF
#define NS_CONFIG_ENABLE_SOFTWARE_CSMA_BACKOFF 1
#endif
#endif // NS_RADIO

#define NS_CONFIG_ENABLE_PLATFORM_USEC_TIMER 1

#define NS_CONFIG_PLATFORM_ASSERT_MANAGEMENT 1

#endif // NS_CORE_UNIX_CONFIG_H_
